version: '3.8'
services:
    db:
        image: mariadb:10.5.8
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - mariadb_data:/var/lib/mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: illusory_wall
        restart: unless-stopped

    illusorywall:
        image: link00000000/illusorywall:latest
        container_name: illusorywall
        links:
            - db
        depends_on:
            - db
        restart: unless-stopped
        environment:
            'ConnectionStrings:DefaultConnection': 'server=db;port=3306;user=user;password=user;database=illusory_wall'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        links:
            - db
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: user
            PMA_PASSWORD: user
            PMA_ARBIRARY: 1
        restart: 'no'

    caddy:
        build: ./caddy
        container_name: caddy
        volumes:
            - caddy_data:/data
            - caddy_config:/config
        ports:
            - 80:80
            - 443:443

volumes:
    mariadb_data:
    caddy_data:
    caddy_config:
