version: '3.8'
services:
    db:
        build: ./db
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./.mysql_data:/var/lib/mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: illusory_wall
        ports:
            - 3306:3306
        restart: on-failure

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        links:
            - db
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_ARBIRARY: 1
        ports:
            - 8080:80
        restart: on-failure

    illusorywall:
        build: ./IllusoryWall
        container_name: illusorywall
        links:
            - db
        depends_on:
            - db
        ports:
            - 80:80
        restart: on-failure
