version: '3.8'
services:
    db:
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: phpmyadmin
        links:
            - db
        depends_on:
            - db
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: illusorywall
            PMA_PASSWORD: illusorywall
            PMA_ARBIRARY: 1
        ports:
            - 8080:80
        restart: on-failure
