version: '3.8'
services:
    db:
        build: ./db
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        volumes:
            - ./.mysql_data:/var/lib/mysql
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: illusory_wall
        restart: unless-stopped

    illusorywall:
        build: ./IllusoryWall
        container_name: illusorywall
        links:
            - db
        depends_on:
            - db
        ports:
            - 80:80
        restart: unless-stopped
